### ISSUE TITLE
Add machine-id to query

### ISSUE THREAD

**Issue by zeke** [electron/update-electron-app#14]
https://github.com/automation-stack/node-machine-id

**Comment by juliangruber** [comment]
maybe as a query string? `feedUrl += ?id=`? Not sure how to do it otherwise, with the `auto-updater` module.

**Comment by zeke** [comment]
Yeah was thinking query string. This piece of data will help us identify how many consumers of the new service are using the `update-electron-app` module. Also it will always be the same string, whereas a user's IP address will change.

**Comment by MarshallOfSound** [comment]
This is awkward territory (effectively taking tracking Id's from users machines) this needs to be extremely clearly documented 👍 along with a privacy policy covering how these id's would be used

**Comment by timfish** [comment]
`node-machine-id` also has [this issue](https://github.com/automation-stack/node-machine-id/issues/27) which means it doesn't work on Windows machines with registry editing disabled.
