### ISSUE TITLE
Is this going to work on Linux Distributions?

### ISSUE THREAD

**Issue by chesucr** [electron/update-electron-app#24]
As the title says, I am wondering if there is a plan to make this work on some Linux Distribution or if the app already works.

Thanks to make the electron autoupdate more straightforward.

**Comment by zeke** [comment]
This module is not likely to support linux any time soon, as Electron's `autoUpdater` API doesn't have support for Linux and there is no plan to add it.

We need better documentation on the Electron site about the various options for autoUpdating Linux apps. I've created an issue for it here: https://github.com/electron/electron/issues/12796

**Comment by zeke** [comment]
PS thanks for asking. 👍
