### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by linxu** [electron/update-electron-app#27]
can you provide a project demo or a detailed tutorial？

**Comment by malept** [comment]
There's an example Electron app at the [`update.electronjs.org` repo](https://github.com/electron/update.electronjs.org/tree/master/example).

**Comment by zeke** [comment]
Usage of this module is documented in the readme: https://github.com/electron/update-electron-app#readme

If you have specific questions about usage, please open new issues describing any problems you're having.
