### ISSUE TITLE
Auto updater repo option

### ISSUE THREAD

**Issue by tigierrei** [electron/update-electron-app#31]
I'm currently trying to implement an auto-update function in my app using electron-release-server.
Since I'm not using a repository on github, what should I put in the repo field of the options? Because if I don't set it the module triggers an error

**Comment by tigierrei** [comment]
@zeke

**Comment by zeke** [comment]
https://github.com/ArekSredzki/electron-release-server is an unrelated project. If you're having problems with it, you should open an issue on that repo.

However, If you want to use the `update-electron-app` but your project is not open source or doesn't live in a GitHub repo, you can do this: https://github.com/electron/update-electron-app#can-i-use-this-module-by-uploading-my-private-apps-builds-to-a-public-github-repository
