### ISSUE TITLE
log in the renderer process

### ISSUE THREAD

**Issue by zeke** [electron/update-electron-app#4]
The current recommendation is to call `require('update-electron-app')({repo: 'some/repo'}) from the main process, but calls to `console.log` from a packaged app will just go into the ether.

Maybe something [electron-log](https://ghub.io/electron-log) would be a good fit for this.

**Comment by MarshallOfSound** [comment]
Something pretty standard would be to add a "logger" option that just has to expose the standard logging methods that most logging utils use.

".log" / ".info" Etc.

Then just default to `console.log` if one is not provided

**Comment by zeke** [comment]
Oh, missed this comment before opening #6. Let me know what you think of that and whether I should still go for the `logger` option.

**Comment by juliangruber** [comment]
I would prefer the `logger` option as well :+1:
