### ISSUE TITLE
Add CFA support

### ISSUE THREAD

**Issue by malept** [electron/update-electron-app#45]
We had some issues releasing a new version recently (see #41). For other modules under the Docs & Tools WG (such as `electron-winstaller`, `node-rcedit`, and `asar`), we have added CFA-based semantic-release support to increase the bus factor. We should add CFA support for this module as well.

CC: @MarshallOfSound who is effectively the CFA administrator :smile:

**Comment by quanganh1906** [comment]
cảm ơn
