### ISSUE TITLE
Can someone creates the step by step of how to use it ?

### ISSUE THREAD

**Issue by sostenesapollo** [electron/update-electron-app#53]
I want to use it on my private repo to update my app automatically but where I can find the Documentation ? :(

**Comment by juliangruber** [comment]
This service only works with public repos, however you can create a public repo just for the releases and still keep your code repo private. This repo's README _should_ have all the information you need (also about the public / private repos), can you tell us what is missing?

**Comment by sostenesapollo12** [comment]
Yeah I more or less understand... 
1- Create private repo
2- Create a public repo with readme that provides the information about my private repository
3- `This repo's README should have all the information you need (also about the public / private repos)`

Can you tell me more about the last part ?

**Comment by juliangruber** [comment]
> This repo's README _should_ have all the information you need (also about the public / private repos),

By that I meant https://github.com/electron/update-electron-app/blob/master/readme.md. Have you set up the requirements? https://github.com/electron/update-electron-app#requirements
