### ISSUE TITLE
update-electron-app config looks good; aborting updates since app is in development mode

### ISSUE THREAD

**Issue by AntonGilfyole** [electron/update-electron-app#69]
```
const { app, BrowserWindow, Menu } = require('electron')

// set env
process.env.NODE_ENV = 'production'
const isDev = process.env.NODE_ENV !== 'production' ? true : false
const isMac = process.platform === 'darwin' ? true : false

// Enable live reload for all the files inside project directory
if (process.env.NODE_ENV === 'development') { require('electron-reload')(__dirname) };
```
when i run the apps, terminal log : update-electron-app config looks good; aborting updates since app is in development mode

**Comment by erickzhao** [comment]
Hey @AntonGilfyole, setting `process.env.NODE_ENV = 'production'` won't simulate a production environment for your app.

Internally, `update-electron-app` uses the `electron-is-dev` utility, which draws from Electron's `app.isPackaged` [readonly variable](https://www.electronjs.org/docs/api/app#appispackaged-readonly).

According to the [`electron-is-dev` source code](https://github.com/sindresorhus/electron-is-dev/blob/c9b844127f350cde547ca4a0ac8f6849cfa07f22/index.js#L11), you should be able to override the boolean by setting `process.env.ELECTRON_IS_DEV = 0".

If you have any other problems, we can reopen the issue.
