### ISSUE TITLE
detect repository in package.json

### ISSUE THREAD

**Issue by zeke** [electron/update-electron-app#9]
In the current implementation, `repo` is a required option. We could attempt to look for it in a `package.json` file, and parse it using [github-url-to-object](http://ghub.io/github-url-to-object) or similar. I would be in favor of looking for the `package.json` in the `process.cwd()` or similar, and failing fast if it's not there, rather than trying to move up the directory tree in search of another `package.json` file.

**Comment by malept** [comment]
FYI, if you choose to search up the directory tree, Electron Packager uses [`get-package-info`](https://www.npmjs.com/package/get-package-info) to accomplish this.

**Comment by timfish** [comment]
Is the app `package.json` not always at `path.join(app.getAppPath(), 'package.json')`?

**Comment by zeke** [comment]
Apps using `electron-builder` have two package.json files:

```
.
├── app
│   └── package.json
└── package.json
```

The `app` directory is what is packaged and the top-level `package.json`, which usually contains info like `repository`, is omitted.

**Comment by timfish** [comment]
That's structure is equally common if you're building an app in a mono-repository. 

Once apps using the two (or more) `package.json` structure are packaged, the top level `package.json` shipped with the app will be the one in `app`.  The repository top-level `package.json` doesn't get shipped with the app so there is nothing to find if you look higher up than 'getAppPath()`.

**Comment by zeke** [comment]
So yeah we should look in `path.join(app.getAppPath(), 'package.json')` and give up after that.

**Comment by timfish** [comment]
My explanation was a rather complicated way of saying that when the app gets packaged, `app` becomes the root 😆
